In [66]:
DF_PATH=r"E:\Project\claened.pkl"

In [67]:
# Load packages
import pandas as pd 
import numpy as np
import logging
import pickle
import random
import plotly 
import os
from pathlib import Path

import mlflow
from mlflow.tracking import MlflowClient

from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler
from sklearn.pipeline import make_pipeline, FeatureUnion
from sklearn.feature_selection import VarianceThreshold
from sklearn.multioutput import MultiOutputClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

from sklearn import metrics
from sklearn.metrics import auc, accuracy_score, confusion_matrix, f1_score, precision_score, recall_score

from sklearn.decomposition import PCA, KernelPCA

from sklearn import tree
from sklearn.linear_model import LogisticRegression

from matplotlib import pyplot as plt

In [68]:
def calculate_quality(ground_truth, predictions, metric_function, sort_values=False):
    quality_scores = {}
    for col in predictions.columns:
        role_pred  = predictions[col].copy()
        role_truth = ground_truth[col].copy()
        quality_scores[col] = round(metric_function(role_truth, role_pred) * 100, 2)
        
    quality_scores = pd.Series(quality_scores.values(), index=quality_scores.keys())
    if sort_values:
        quality_scores = quality_scores.sort_values()
    
    return quality_scores

In [69]:
df=pd.read_pickle(DF_PATH)

In [70]:
df

                  DevType                           \
      Academic researcher Data or business analyst
0                       0                        0
3                       0                        0
4                       0                        0
8                       0                        0
9                       0                        0
...                   ...                      ...
83434                   0                        0
83435                   0                        0
83436                   0                        0
83437                   0                        0
83438                   0                        0

                                                                            \
      Data scientist or machine learning specialist Database administrator
0                                                 0                      0
3                                                 0                      0
4                                                 0                      0
8                                                 0                      0
9                                                 1                      0
...                                             ...                    ...
83434                                             0                      0
83435                                             0                      0
83436                                             1                      0
83437                                             0                      0
83438                                             0                      0

                                                                   \
      DevOps specialist Developer, QA or test Developer, back-end
0                     0                     0                   0
3                     0                     0                   0
4                     0                     0                   0
8                     0                     0                   0
9                     0                     0                   0
...                 ...                   ...                 ...
83434                 0                     0                   1
83435                 0                     0                   0
83436                 1                     0                   0
83437                 0                     0                   1
83438                 0                     0                   1

                                                     \
      Developer, desktop or enterprise applications
0                                                 0
3                                                 0
4                                                 1
8                                                 0
9                                                 0
...                                             ...
83434                                             0
83435                                             0
83436                                             0
83437                                             0
83438                                             0

                                                                        ...  \
      Developer, embedded applications or devices Developer, front-end  ...
0                                               0                    0  ...
3                                               0                    1  ...
4                                               0                    0  ...
8                                               0                    1  ...
9                                               0                    0  ...
...                                           ...                  ...  ...
83434                                           0                    0  ...
83435                                           0                    0  ...
83436                                           0                    0  ...
83437                                           0                    0  ...
83438                                           0                    1  ...

      skills_clusters                                                 \
      skills_group_20 skills_group_21 skills_group_22 skills_group_3
0                   0               0               0              4
3                   0               0               0              0
4                   0               0               0              0
8                   0               0               0              0
9                   0               0               3              0
...               ...             ...             ...            ...
83434               0               0               0              0
83435               0               0               0              4
83436               0               0               1              0
83437               0               0               2              0
83438               1               1               0              0

                                                                   \
      skills_group_4 skills_group_5 skills_group_6 skills_group_7
0                  0              1              2              0
3                  0              0              2              0
4                  0              4              1              2
8                  0              4              2              0
9                  0              2              1              0
...              ...            ...            ...            ...
83434              1              3              1              0
83435              1              2              2              1
83436              0              5              1              2
83437              0              3              1              3
83438              0              3              3              0


      skills_group_8 skills_group_9
0                  0              0
3                  0              0
4                  0              0
8                  0              0
9                  0              0
...              ...            ...
83434              0              0
83435              1              0
83436              0              2
83437              0              2
83438              0              0

[46412 rows x 164 columns]

In [71]:
# Check the total samples of roles
roles_df = df["DevType"].copy()
roles_df.sum(axis=0)

Academic researcher                               1708
Data or business analyst                          1658
Data scientist or machine learning specialist     2460
Database administrator                            1210
DevOps specialist                                 3056
Developer, QA or test                             1135
Developer, back-end                              17084
Developer, desktop or enterprise applications     4845
Developer, embedded applications or devices       2138
Developer, front-end                              8932
Developer, full-stack                            20655
Developer, game or graphics                        899
Developer, mobile                                 4751
Engineer, data                                    1941
Scientist                                         1046
System administrator                              2069
dtype: int64

In [72]:
# Resample roles
samples_per_class = 1200
resampled_roles = []

for role_col in roles_df.columns:
    sub_df = roles_df.loc[roles_df[role_col] == 1].copy()
    
    if len(sub_df) < samples_per_class:
        # Upsample
        sub_df = sub_df.sample(samples_per_class, replace=True, random_state=0)
    else:
        # Downsample
        sub_df = sub_df.sample(samples_per_class, random_state=0) 
    
    resampled_roles.append(sub_df)

In [73]:
# Construct dfs
roles_df  = pd.concat(resampled_roles)
df = df.loc[roles_df.index].copy()

In [74]:
roles_df.sum(axis=0)

Academic researcher                              2280
Data or business analyst                         1965
Data scientist or machine learning specialist    2576
Database administrator                           1765
DevOps specialist                                2170
Developer, QA or test                            1514
Developer, back-end                              5710
Developer, desktop or enterprise applications    2690
Developer, embedded applications or devices      1773
Developer, front-end                             2614
Developer, full-stack                            5602
Developer, game or graphics                      1441
Developer, mobile                                2155
Engineer, data                                   2046
Scientist                                        1910
System administrator                             2110
dtype: int64

In [75]:
X_train, X_test, Y_train, Y_test = train_test_split(df.drop("DevType", axis=1), 
                                                    df["DevType"], 
                                                    random_state=0)

C:\Users\DELL\AppData\Local\Temp\ipykernel_13528\1098765831.py:1: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  X_train, X_test, Y_train, Y_test = train_test_split(df.drop("DevType", axis=1),

In [90]:
MLFLOW_TRACKING_URI = '../models/mlruns'
MLFLOW_EXPERIMENT_NAME = "skills_jobs_stackoverflow"

LOG_PATH = "../models/temp/"
LOG_DATA_PKL    =  "data.pkl"
LOG_MODEL_PKL   =  "model.pkl"
LOG_METRICS_PKL =  "metrics.pkl"

In [91]:
# Initialize client and experiment
mlflow.set_tracking_uri(MLFLOW_TRACKING_URI)
client = MlflowClient()
mlflow.get_experiment_by_name(MLFLOW_EXPERIMENT_NAME)
exp = client.get_experiment_by_name(MLFLOW_EXPERIMENT_NAME)

In [92]:
clf = make_pipeline(StandardScaler(),
                    MultiOutputClassifier(LogisticRegression()))

clf.fit(X_train.values, Y_train.values)
predictions =  pd.DataFrame(clf.predict(X_train.values),
                            columns=Y_train.columns)

In [93]:
# Evaluate on training set
predictions =  pd.DataFrame(clf.predict(X_train.values),
                            columns=Y_train.columns)
train_scores = {score.__name__: calculate_quality(Y_train, predictions, score) 
                for score in [accuracy_score, precision_score, recall_score, f1_score]}
train_scores = pd.concat(train_scores,axis=1)

In [94]:
# Evaluate on test set
predictions =  pd.DataFrame(clf.predict(X_test.values), columns=Y_test.columns)
test_scores = {score.__name__: calculate_quality(Y_test, predictions, score) 
                for score in [accuracy_score, precision_score, recall_score, f1_score]}
test_scores = pd.concat(test_scores,axis=1)
mean_test_scores = test_scores.mean()

In [95]:
print(mean_test_scores)
test_scores

accuracy_score     88.940625
precision_score    62.217500
recall_score       29.916875
f1_score           38.644375
dtype: float64

,accuracy_score,precision_score,recall_score,f1_score
Academic researcher,90.06,64.91,30.94,41.90
Data or business analyst,91.12,65.99,26.58,37.90
Data scientist or machine learning specialist,89.96,67.58,49.23,56.96
Database administrator,90.90,56.10,5.20,9.52
DevOps specialist,90.23,65.55,25.66,36.88
"Developer, QA or test",91.69,25.00,0.51,0.99
"Developer, back-end",74.40,62.64,35.72,45.50
"Developer, desktop or enterprise applications",87.52,61.58,18.20,28.09
"Developer, embedded applications or devices",92.67,64.95,33.41,44.13
"Developer, front-end",88.40,67.91,36.76,47.70
"Developer, full-stack",78.46,65.48,55.08,59.83
"Developer, game or graphics",94.81,76.82,46.05,57.58
"Developer, mobile",93.08,74.75,57.12,64.76
"Engineer, data",90.25,61.18,18.53,28.44
Scientist,90.12,54.75,24.44,33.80
System administrator,89.38,60.29,15.24,24.33

In [96]:
# Data details
data_details = {"data_path": DF_PATH,
                "training_indices": X_train.index.tolist(),
                "test_indices":     X_test.index.tolist(), 
                "features_names":   X_train.columns.droplevel(0).tolist(),
                "targets_names":    Y_train.columns.tolist()}

with open(os.path.join(LOG_PATH, LOG_DATA_PKL), "wb") as output_file:
    pickle.dump(data_details, output_file)

In [97]:
# Model
model = {"model_description": "Baseline model: Logistic Regression ",
         "model_details": str(clf),
         "model_object": clf} 

with open(os.path.join(LOG_PATH, LOG_MODEL_PKL), "wb") as output_file:
    pickle.dump(model, output_file)

In [98]:
# Performance details
classes_metrics = {"train_scores": train_scores, 
                   "test_scores":  test_scores}

with open(os.path.join(LOG_PATH, LOG_METRICS_PKL), "wb") as output_file:
    pickle.dump(classes_metrics, output_file)